name: CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  cancel-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  static-check:
    runs-on: ubuntu-latest
    needs: cancel-workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Clean build
        run: ./gradlew clean
      - name: Run ktlintDebug
        run: ./gradlew ktlintMainSourceSetCheck
      - name: Upload ktlint report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ktlint-result
          path: ./**/build/reports/ktlint/**/*.html

  build:
    runs-on: ubuntu-latest
    needs: static-check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Clean build
        run: ./gradlew clean
      - name: Setup secrets.xml
        run: |
          mkdir -p ./app/src/main/res/values
          cat << EOF > ./app/src/main/res/values/secrets.xml
          ${{ secrets.secrets_xml }}
          EOF
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace